<?php

/**
 * Implementation of hook_field_info()
 * 
 * @return array - field definition
 */
function cmis_field_field_info() {
  return array(
    'cmis_field_path' => array(
      'label' => t('CMIS Field'),
      'description' => t('Attach a CMIS object to a Drupal entity'),
      'default_widget' => 'cmis_field_widget',
      'default_formatter' => 'cmis_field_link',
      'instance settings' => array('cmis_field_rootFolderPath' => ''), 
    )
  );
}

/**
 * Implements hook_field_validate().
 *
 * For now, just validates that the field isn't empty.
 */
function cmis_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!empty($item['cmis_field_path'])) {
      if (1 == 0) {
        $errors[$field['cmis_field']][$langcode][$delta][] = array(
          'error' => 'cmis_field_invalid',
          'message' => t('You are in the anti-universe, where 1 == 0.'),
        );
      }
    }
  }
}

/**
 * Implementation of hook_is_empty()
 * 
 * @param $item - field value(s)
 * @param $field - field settings
 * @return boolean - TRUE/FALSE
 */
function cmis_field_field_is_empty($item, $field) {
  return empty($item['path']);
}

/**
 * Implementation of hook_instance_settings_form()
 * 
 * @param $op - operation
 * @param $field - field beign operated on
 * @return - form or settings array dependent on operation
 */
function cmis_field_field_instance_settings_form($field, $instance) {
  drupal_add_library('system', 'ui.dialog');
  $settings = $instance['settings'];
  
  $form['cmis_field_rootFolderPath'] = array(
    '#title' => t('Root Directory'),
    '#description' => t('Root folder for CMIS nodes'),
    '#type' => 'textfield',
    '#default_value' => $settings['cmis_field_rootFolderPath'],
    '#suffix' => '<div id="cmis_field_rootfolderpath_dialog" style="display:none"></div>',
    //there is only one so we can set the id here...
    '#attributes' => array('class' => array('cmis-field-setting')),
  );
  
  $form['#attached']['js'] = array(
    array('data' => drupal_get_path('module', 'cmis_field') . '/js/cmis_field.js'),
  );
  
  return $form;
}

/**
 * Implementation of hook_field_widget_info
 * 
 * @return array defining the widget
 */
function cmis_field_field_widget_info() {
  return array(
    'cmis_field_browser' => array(
      'label' => t('CMIS link'),
      'field types' => array('cmis_field_path'),
      //'settings' => array('cmis_field_rootFolderPath' => array()),
    )
  );
}


/**
 * Implementation of hook_field_widget_form()
 * 
 * @param $element - the form element array
 * @param $edit - 
 * @param $form_state - form state array
 * @param $form - form array
 * @return array - form element
 */
function cmis_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  drupal_add_library('system', 'ui.dialog');
  $title = isset($items[$delta]['title']) ? $items[$delta]['title'] : '';
  $path = isset($items[$delta]['path']) ? $items[$delta]['path'] : '';
  $element += array(
    '#delta' => $delta,
  );
  $element['path'] = array();
  $element['title'] = array();

  $element['title'] += array(
    '#type' => 'textfield',
    '#default_value' => $title,
    '#title' => $element['#title'],
    '#description' => $element['#description'],
    '#default_value' => $title,
    '#required' => $element['#required'],
    '#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
    '#delta' => $delta,
  );
  $element['path'] += array(
    '#type' => 'hidden',
    '#attributes' => array('id' => 'edit-field-cmis-path'),
    '#default_value' => $path,
    '#delta' => $delta,
  );
  
  $element['#attached']['js'] = array(
    array('data' => drupal_get_path('module', 'cmis_field') . '/js/cmis_field.js'),
    array('data' => array('cmispath' => $instance['settings']['cmis_field_rootFolderPath']), 'type' => 'setting'),
  );

  return $element;
}

/**
 * Implementation of hook_field_formatter_info()
 * 
 * @return array
 */
function cmis_field_field_formatter_info() {
  return array(
    'cmis_field_link' => array(
       'label' => t('CMIS link'),
       'field types' => array('cmis_field_path'),
    ),
    'cmis_field_image' => array(
        'label' => t('CMIS image'),
        'field types' => array('cmis_field_path'),
    ),
  );
}


/**
 * Implements hook_field_formatter_view().
 * 
 */

function cmis_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'cmis_field_link':
      foreach ($items as $delta => $item) {
        $element[$delta]['#markup'] = l($item['title'], 'cmis/browser', array('query' => array('id'=> $item['path'])));
      }
      break;
    case 'cmis_field_image':
      foreach ($items as $delta => $item) {
        $element[$delta]['#markup'] = '<img src="' . '/cmis/browser?id=' . $item['path'] . '" style="max-width: 100%"/>';
      }
      break;
  }
  return $element;
}